"""listing job persistence (ISSUE-0030)

Revision ID: 6420ac5f02e7
Revises: 4a2a261611d9
Create Date: 2026-06-05 15:52:02.571116

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6420ac5f02e7'
down_revision: str | None = '4a2a261611d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_job',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('modifiers', sa.JSON(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('ratio', sa.String(length=16), nullable=False),
    sa.Column('size', sa.String(length=16), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_job_created_at'), 'listing_job', ['created_at'], unique=False)
    op.create_index(op.f('ix_listing_job_platform'), 'listing_job', ['platform'], unique=False)
    op.create_index(op.f('ix_listing_job_status'), 'listing_job', ['status'], unique=False)
    op.create_index(op.f('ix_listing_job_user_id'), 'listing_job', ['user_id'], unique=False)
    op.create_table('listing_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('image_key', sa.String(length=128), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['listing_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_image_job_id'), 'listing_image', ['job_id'], unique=False)
    op.create_table('listing_job_input',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('upload_key', sa.String(length=128), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['listing_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_job_input_job_id'), 'listing_job_input', ['job_id'], unique=False)
    # 注：autogenerate 对 app_user.email 的 unique/index 重排为 sqlite 反射假 diff，已删除——
    # 本迁移零改动现有表（ISSUE-0030 硬约束）。
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_job_input_job_id'), table_name='listing_job_input')
    op.drop_table('listing_job_input')
    op.drop_index(op.f('ix_listing_image_job_id'), table_name='listing_image')
    op.drop_table('listing_image')
    op.drop_index(op.f('ix_listing_job_user_id'), table_name='listing_job')
    op.drop_index(op.f('ix_listing_job_status'), table_name='listing_job')
    op.drop_index(op.f('ix_listing_job_platform'), table_name='listing_job')
    op.drop_index(op.f('ix_listing_job_created_at'), table_name='listing_job')
    op.drop_table('listing_job')
    # ### end Alembic commands ###
