"""initial 10 tables

Revision ID: f12587232511
Revises: 
Create Date: 2026-05-28 17:18:11.355878

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f12587232511'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_ledger_created_at'), 'cost_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_cost_ledger_user_id'), 'cost_ledger', ['user_id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('brand_color', sa.String(length=32), nullable=True),
    sa.Column('common_styles', sa.JSON(), nullable=False),
    sa.Column('common_taboos', sa.JSON(), nullable=False),
    sa.Column('common_sizes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_table('model_config',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_customer_id'), 'project', ['customer_id'], unique=False)
    op.create_index(op.f('ix_project_status'), 'project', ['status'], unique=False)
    op.create_table('asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_project_id'), 'asset', ['project_id'], unique=False)
    op.create_table('brief',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('material_types', sa.JSON(), nullable=False),
    sa.Column('sizes', sa.JSON(), nullable=False),
    sa.Column('styles', sa.JSON(), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('bleed', sa.String(length=32), nullable=True),
    sa.Column('copy_text', sa.Text(), nullable=True),
    sa.Column('taboo', sa.Text(), nullable=True),
    sa.Column('delivery', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_project_id'), 'brief', ['project_id'], unique=False)
    op.create_table('deliverable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('fmt', sa.String(length=16), nullable=False),
    sa.Column('files', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverable_project_id'), 'deliverable', ['project_id'], unique=False)
    op.create_table('generation_job',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('customer', sa.String(length=128), nullable=False),
    sa.Column('subscene', sa.String(length=8), nullable=False),
    sa.Column('family', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('used_model', sa.String(length=32), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('positive_prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_job_category'), 'generation_job', ['category'], unique=False)
    op.create_index(op.f('ix_generation_job_family'), 'generation_job', ['family'], unique=False)
    op.create_index(op.f('ix_generation_job_project_id'), 'generation_job', ['project_id'], unique=False)
    op.create_index(op.f('ix_generation_job_status'), 'generation_job', ['status'], unique=False)
    op.create_index(op.f('ix_generation_job_style'), 'generation_job', ['style'], unique=False)
    op.create_index(op.f('ix_generation_job_tier'), 'generation_job', ['tier'], unique=False)
    op.create_index(op.f('ix_generation_job_used_model'), 'generation_job', ['used_model'], unique=False)
    op.create_index(op.f('ix_generation_job_user_id'), 'generation_job', ['user_id'], unique=False)
    op.create_table('revision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_project_id'), 'revision', ['project_id'], unique=False)
    op.create_table('generated_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('kept', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_image_job_id'), 'generated_image', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_image_job_id'), table_name='generated_image')
    op.drop_table('generated_image')
    op.drop_index(op.f('ix_revision_project_id'), table_name='revision')
    op.drop_table('revision')
    op.drop_index(op.f('ix_generation_job_user_id'), table_name='generation_job')
    op.drop_index(op.f('ix_generation_job_used_model'), table_name='generation_job')
    op.drop_index(op.f('ix_generation_job_tier'), table_name='generation_job')
    op.drop_index(op.f('ix_generation_job_style'), table_name='generation_job')
    op.drop_index(op.f('ix_generation_job_status'), table_name='generation_job')
    op.drop_index(op.f('ix_generation_job_project_id'), table_name='generation_job')
    op.drop_index(op.f('ix_generation_job_family'), table_name='generation_job')
    op.drop_index(op.f('ix_generation_job_category'), table_name='generation_job')
    op.drop_table('generation_job')
    op.drop_index(op.f('ix_deliverable_project_id'), table_name='deliverable')
    op.drop_table('deliverable')
    op.drop_index(op.f('ix_brief_project_id'), table_name='brief')
    op.drop_table('brief')
    op.drop_index(op.f('ix_asset_project_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_project_status'), table_name='project')
    op.drop_index(op.f('ix_project_customer_id'), table_name='project')
    op.drop_table('project')
    op.drop_table('model_config')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_cost_ledger_user_id'), table_name='cost_ledger')
    op.drop_index(op.f('ix_cost_ledger_created_at'), table_name='cost_ledger')
    op.drop_table('cost_ledger')
    # ### end Alembic commands ###
