/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description 当前用户（需 Bearer JWT）。无/坏令牌→401。
         */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate
         * @description 出图：薄控制器，只做 HTTP↔用例 翻译，业务在 pipeline 内。
         */
        post: operations["generate_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/cost-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cost Preview
         * @description 出图前成本预估（PRD §3.10），只读不预扣。
         */
        post: operations["cost_preview_generate_cost_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue
         * @description 入队即返回 job_id；进度经 SSE 查询。
         */
        post: operations["enqueue_generate_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_generate__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Customers */
        get: operations["list_customers_customers_get"];
        put?: never;
        /** Create Customer */
        post: operations["create_customer_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Status */
        put: operations["update_status_projects__project_id__status_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Jobs */
        get: operations["list_project_jobs_projects__project_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Images */
        get: operations["list_project_images_projects__project_id__images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brief */
        get: operations["get_brief_projects__project_id__brief_get"];
        /** Put Brief */
        put: operations["put_brief_projects__project_id__brief_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_projects__project_id__assets_get"];
        put?: never;
        /** Upload Asset */
        post: operations["upload_asset_projects__project_id__assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Under Project
         * @description 项目下出图：合成域 Brief→复用 pipeline→落库挂 project_id+round_no。
         */
        post: operations["generate_under_project_projects__project_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Images */
        get: operations["list_images_jobs__job_id__images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/images/{image_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score Image */
        post: operations["score_image_jobs__job_id__images__image_id__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/images/{image_id}/keep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Keep Image */
        post: operations["keep_image_jobs__job_id__images__image_id__keep_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/usable-rate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usable Rate */
        get: operations["usable_rate_jobs__job_id__usable_rate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Project */
        post: operations["export_project_projects__project_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{image_id}/resize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resize Image */
        post: operations["resize_image_images__image_id__resize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Revisions */
        get: operations["list_revisions_projects__project_id__revisions_get"];
        put?: never;
        /** Open Revision */
        post: operations["open_revision_projects__project_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revisions/{revision_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_revisions__revision_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revisions/{revision_id}/items/{seq}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Toggle Item */
        put: operations["toggle_item_revisions__revision_id__items__seq__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cost */
        get: operations["cost_dashboard_cost_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_admin_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Model */
        put: operations["update_model_admin_models__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set User Role */
        put: operations["set_user_role_admin_users__user_id__role_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddItemRequest */
        AddItemRequest: {
            /** Text */
            text: string;
            /** Related Image Id */
            related_image_id?: number | null;
        };
        /**
         * AssetKind
         * @enum {string}
         */
        AssetKind: "产品图" | "参考图";
        /** AssetOut */
        AssetOut: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            kind: components["schemas"]["AssetKind"];
            /** Url */
            url: string;
        };
        /** Body_upload_asset_projects__project_id__assets_post */
        Body_upload_asset_projects__project_id__assets_post: {
            /** File */
            file: string;
            kind: components["schemas"]["AssetKind"];
        };
        /** BriefOut */
        BriefOut: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Material Types */
            material_types: string[];
            /** Sizes */
            sizes: string[];
            /** Styles */
            styles: string[];
            /** Resolution */
            resolution: string | null;
            /** Bleed */
            bleed: string | null;
            /** Copy Text */
            copy_text: string | null;
            /** Taboo */
            taboo: string | null;
            /** Delivery */
            delivery: {
                [key: string]: unknown;
            };
        };
        /** BriefUpsert */
        BriefUpsert: {
            /** Material Types */
            material_types?: string[];
            /** Sizes */
            sizes?: string[];
            /** Styles */
            styles?: string[];
            /** Resolution */
            resolution?: string | null;
            /** Bleed */
            bleed?: string | null;
            /** Copy Text */
            copy_text?: string | null;
            /** Taboo */
            taboo?: string | null;
            /** Delivery */
            delivery?: {
                [key: string]: unknown;
            };
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "3C数码" | "服饰配件" | "美妆护肤" | "食品" | "含人物" | "镜面玻璃";
        /** CostPreviewResponse */
        CostPreviewResponse: {
            tier: components["schemas"]["Tier"];
            /** Candidate Count */
            candidate_count: number;
            model: components["schemas"]["ModelName"];
            /** Estimated Cost */
            estimated_cost: string;
            /** Month Used */
            month_used: string;
            /** Month Budget */
            month_budget: string;
        };
        /** CustomerCreate */
        CustomerCreate: {
            /** Name */
            name: string;
            /** Contact */
            contact?: string | null;
            /** Industry */
            industry?: string | null;
            /** Brand Color */
            brand_color?: string | null;
            /** Common Styles */
            common_styles?: string[];
            /** Common Taboos */
            common_taboos?: string[];
            /** Common Sizes */
            common_sizes?: string[];
        };
        /** CustomerOut */
        CustomerOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Contact */
            contact: string | null;
            /** Industry */
            industry: string | null;
            /** Brand Color */
            brand_color: string | null;
            /** Common Styles */
            common_styles: string[];
            /** Common Taboos */
            common_taboos: string[];
            /** Common Sizes */
            common_sizes: string[];
        };
        /** DesignerOut */
        DesignerOut: {
            /** User Id */
            user_id: string;
            /** Image Count */
            image_count: number;
            /** Cost */
            cost: string;
            /** Usable */
            usable: number;
            /** Scored */
            scored: number;
            /** Usable Rate */
            usable_rate: number;
        };
        /**
         * Dimension
         * @enum {string}
         */
        Dimension: "overview" | "model" | "project" | "designer" | "tier";
        /** ExportFileOut */
        ExportFileOut: {
            /** Filename */
            filename: string;
            /** Url */
            url: string;
        };
        /**
         * ExportFormat
         * @enum {string}
         */
        ExportFormat: "jpg" | "png" | "pdf";
        /** ExportRequest */
        ExportRequest: {
            /** Image Ids */
            image_ids: number[];
            /** Formats */
            formats: components["schemas"]["ExportFormat"][];
            resize?: components["schemas"]["ResizeSpec"] | null;
            /**
             * Zip
             * @default false
             */
            zip: boolean;
        };
        /** ExportResponse */
        ExportResponse: {
            /** Package Url */
            package_url: string | null;
            /** Files */
            files: components["schemas"]["ExportFileOut"][];
        };
        /**
         * GenerateRequest
         * @description HTTP 边界输入；负责把传输层 DTO 翻译成领域 Brief（边界即校验点）。
         */
        GenerateRequest: {
            /** Customer */
            customer: string;
            subscene: components["schemas"]["SubScene"];
            family: components["schemas"]["TemplateFamily"];
            tier: components["schemas"]["Tier"];
            style: components["schemas"]["Style"];
            category: components["schemas"]["Category"];
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * N
             * @default 6
             */
            n: number;
            /** Copy Text */
            copy_text?: string | null;
            /** Taboo */
            taboo?: string | null;
            /** Product Desc */
            product_desc?: string | null;
            /** Brand Name */
            brand_name?: string | null;
        };
        /** GenerateResponse */
        GenerateResponse: {
            used_model: components["schemas"]["ModelName"];
            /** Total Cost */
            total_cost: string;
            /** Positive Prompt */
            positive_prompt: string;
            /** Negative Prompt */
            negative_prompt: string;
            /** Images */
            images: components["schemas"]["GeneratedImageOut"][];
        };
        /** GeneratedImageOut */
        GeneratedImageOut: {
            /** Url */
            url: string;
            /** Seed */
            seed: number;
            /** Latency Ms */
            latency_ms: number;
            /** Cost */
            cost: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageOut */
        ImageOut: {
            /** Id */
            id: number;
            /** Url */
            url: string;
            /** Seed */
            seed: number;
            /** Score */
            score: number | null;
            /** Kept */
            kept: boolean;
        };
        /** KeepRequest */
        KeepRequest: {
            /** Kept */
            kept: boolean;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Jwt */
            jwt: string;
            role: components["schemas"]["Role"];
            /** Name */
            name: string;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /** Dept */
            dept: string | null;
        };
        /** ModelConfigOut */
        ModelConfigOut: {
            /** Name */
            name: string;
            /** Unit Cost */
            unit_cost: string;
            /** Enabled */
            enabled: boolean;
            /** Extra */
            extra: {
                [key: string]: unknown;
            };
        };
        /**
         * ModelConfigUpdate
         * @description 部分更新：仅传入的字段生效（None = 不改）。
         */
        ModelConfigUpdate: {
            /** Unit Cost */
            unit_cost?: number | string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ModelName
         * @enum {string}
         */
        ModelName: "gpt-image-2" | "qwen-image-pro" | "seedream-5" | "wanxiang-2.7-pro" | "lingdong-2";
        /** ModelOut */
        ModelOut: {
            /** Model */
            model: string;
            /** Call Count */
            call_count: number;
            /** Image Count */
            image_count: number;
            /** Cost */
            cost: string;
            /** Cost Share */
            cost_share: number;
            /** Avg Cost */
            avg_cost: string;
        };
        /** OverviewOut */
        OverviewOut: {
            /** Total Images */
            total_images: number;
            /** Total Cost */
            total_cost: string;
            /** Avg Cost */
            avg_cost: string;
            /** Usable Rate */
            usable_rate: number;
        };
        /**
         * Period
         * @enum {string}
         */
        Period: "month" | "week" | "day";
        /** ProjectCreate */
        ProjectCreate: {
            /** Customer Id */
            customer_id: number;
            /** Name */
            name: string;
        };
        /**
         * ProjectGenerateRequest
         * @description 出图配置（D2 方案①）。HTTP 边界翻译成 GenerationConfig；需求单/素材后端补齐。
         */
        ProjectGenerateRequest: {
            subscene: components["schemas"]["SubScene"];
            family: components["schemas"]["TemplateFamily"];
            category: components["schemas"]["Category"];
            tier: components["schemas"]["Tier"];
            style: components["schemas"]["Style"];
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * N
             * @default 6
             */
            n: number;
            /** Asset Ids */
            asset_ids?: number[];
        };
        /** ProjectGenerateResponse */
        ProjectGenerateResponse: {
            /** Job Id */
            job_id: string;
            /** Project Id */
            project_id: number;
            /** Round No */
            round_no: number;
            used_model: components["schemas"]["ModelName"];
            /** Total Cost */
            total_cost: string;
            /** Positive Prompt */
            positive_prompt: string;
            /** Negative Prompt */
            negative_prompt: string;
            /** Images */
            images: components["schemas"]["GeneratedImageOut"][];
        };
        /** ProjectImageOut */
        ProjectImageOut: {
            /** Image Id */
            image_id: number;
            /** Job Id */
            job_id: string;
            /** Url */
            url: string;
            /** Seed */
            seed: number;
            /** Score */
            score: number | null;
            /** Kept */
            kept: boolean;
            /** Round No */
            round_no: number;
            /** Subscene */
            subscene: string;
        };
        /** ProjectJobOut */
        ProjectJobOut: {
            /** Job Id */
            job_id: string;
            /** Round No */
            round_no: number;
            /** Subscene */
            subscene: string;
            /** Family */
            family: string;
            /** Tier */
            tier: string;
            /** Category */
            category: string;
            /** Used Model */
            used_model: string;
            /** Candidate Count */
            candidate_count: number;
            /** Total Cost */
            total_cost: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "需求录入" | "设计中" | "客户审稿" | "已交付";
        /** ProjectStatusUpdate */
        ProjectStatusUpdate: {
            status: components["schemas"]["ProjectStatus"];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /** ResizeRequest */
        ResizeRequest: {
            /** W */
            w: number;
            /** H */
            h: number;
            /** @default png */
            format: components["schemas"]["ExportFormat"];
        };
        /** ResizeResponse */
        ResizeResponse: {
            /** Url */
            url: string;
        };
        /** ResizeSpec */
        ResizeSpec: {
            /** W */
            w: number;
            /** H */
            h: number;
        };
        /** RevisionItemOut */
        RevisionItemOut: {
            /** Seq */
            seq: number;
            /** Text */
            text: string;
            /** Done */
            done: boolean;
            /** Related Image Id */
            related_image_id: number | null;
        };
        /** RevisionOpenRequest */
        RevisionOpenRequest: {
            /** Round No */
            round_no?: number | null;
            /** Deadline */
            deadline?: string | null;
        };
        /** RevisionOut */
        RevisionOut: {
            /** Id */
            id: number;
            /** Project Id */
            project_id: number;
            /** Round No */
            round_no: number;
            status: components["schemas"]["RevisionStatus"];
            /** Deadline */
            deadline: string | null;
            /** Items */
            items: components["schemas"]["RevisionItemOut"][];
        };
        /**
         * RevisionStatus
         * @enum {string}
         */
        RevisionStatus: "进行中" | "已完成";
        /**
         * Role
         * @description 系统角色（PRD §6.3.3）：部门=设计部→设计师；管理层/负责人→管理者；其他→拒。
         * @enum {string}
         */
        Role: "设计师" | "管理者";
        /** RoleUpdate */
        RoleUpdate: {
            role: components["schemas"]["Role"];
        };
        /** ScoreRequest */
        ScoreRequest: {
            /** Score */
            score: number;
        };
        /**
         * Style
         * @enum {string}
         */
        Style: "高端轻奢" | "极简北欧" | "国潮中式" | "科技未来" | "清新自然" | "运动机能" | "喜庆节日";
        /**
         * SubScene
         * @enum {string}
         */
        SubScene: "S1" | "S3" | "S4";
        /**
         * TemplateFamily
         * @enum {string}
         */
        TemplateFamily: "family_1" | "family_2" | "family_3" | "family_4" | "family_5" | "family_6" | "family_7" | "family_8" | "family_9";
        /**
         * Tier
         * @enum {string}
         */
        Tier: "draft" | "standard" | "refine";
        /** TierOut */
        TierOut: {
            /** Tier */
            tier: string;
            /** Image Count */
            image_count: number;
            /** Actual Share */
            actual_share: number;
            /** Target Share */
            target_share: number;
        };
        /** ToggleItemRequest */
        ToggleItemRequest: {
            /** Done */
            done: boolean;
        };
        /** UsableRateOut */
        UsableRateOut: {
            /** Usable */
            usable: number;
            /** Total */
            total: number;
            /** Rate */
            rate: number;
        };
        /**
         * UserOut
         * @description 用户管理列表项。**不含 password_hash**。
         */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ProjectOut */
        design_hub__interface__dashboard_schemas__ProjectOut: {
            /** Project Id */
            project_id: number | null;
            /** Cost */
            cost: string;
            /** Image Count */
            image_count: number;
            /** Designer Count */
            designer_count: number;
            /** Per Capita */
            per_capita: number;
        };
        /** ProjectOut */
        design_hub__interface__project_schemas__ProjectOut: {
            /** Id */
            id: number;
            /** Customer Id */
            customer_id: number;
            /** Name */
            name: string;
            status: components["schemas"]["ProjectStatus"];
            /** Current Round */
            current_round: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_generate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_preview_generate_cost_preview_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_generate_async_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_generate__job_id__events_get: {
        parameters: {
            query?: {
                access_token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_customers_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_customer_customers_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: {
                customer_id?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["design_hub__interface__project_schemas__ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["design_hub__interface__project_schemas__ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["design_hub__interface__project_schemas__ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_projects__project_id__status_put: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["design_hub__interface__project_schemas__ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_jobs_projects__project_id__jobs_get: {
        parameters: {
            query?: {
                round_no?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectJobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_images_projects__project_id__images_get: {
        parameters: {
            query?: {
                round_no?: number | null;
                kept?: boolean | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectImageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brief_projects__project_id__brief_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_brief_projects__project_id__brief_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BriefUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_projects__project_id__assets_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_asset_projects__project_id__assets_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_projects__project_id__assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_under_project_projects__project_id__generate_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string;
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_images_jobs__job_id__images_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_image_jobs__job_id__images__image_id__score_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
                image_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    keep_image_jobs__job_id__images__image_id__keep_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
                image_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usable_rate_jobs__job_id__usable_rate_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsableRateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_project_projects__project_id__export_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resize_image_images__image_id__resize_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                image_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_revisions_projects__project_id__revisions_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_revision_projects__project_id__revisions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionOpenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_item_revisions__revision_id__items_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                revision_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_item_revisions__revision_id__items__seq__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                revision_id: number;
                seq: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cost_dashboard_cost_get: {
        parameters: {
            query?: {
                dim?: components["schemas"]["Dimension"];
                period?: components["schemas"]["Period"];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"] | components["schemas"]["ModelOut"][] | components["schemas"]["design_hub__interface__dashboard_schemas__ProjectOut"][] | components["schemas"]["DesignerOut"][] | components["schemas"]["TierOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_admin_models_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_admin_models__name__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_admin_users_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_role_admin_users__user_id__role_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
