/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description 当前用户（需 Bearer JWT）。无/坏令牌→401。
         */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Listing
         * @description listing 出图（单图 n / 套图 plan 互斥，PRD §3.12.14）：异步返回 job_id。
         */
        post: operations["generate_listing_listing_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone Listing
         * @description 爆款图复刻（PRD §3.13）：产品图==1 + 爆款参考图 1..2，两档复刻，异步返回 job_id。
         */
        post: operations["clone_listing_listing_clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Listing
         * @description 二次编辑（PRD §3.12.13/ISSUE-0040）：基于本人产出图迭代（delta 微调 / full 重做）。
         */
        post: operations["edit_listing_listing_edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description 当前用户的 listing 历史（时间倒序、分页）；q 非空按 prompt/platform 模糊搜本人任务。
         */
        get: operations["list_jobs_listing_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description listing 任务详情（仅本人；非本人 / 不存在 → 404，不泄露存在性）。
         */
        get: operations["get_job_listing_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listing/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listing Events */
        get: operations["listing_events_listing__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Messages
         * @description 发一句话，流式收一轮（帮我设计 Agent 对话入口，方案 C）。Bearer 头鉴权。
         *
         *     事件序：session → assistant_delta* → [step → tool_call → cost_confirm] → assistant_end。
         *     触发出图时在 cost_confirm 暂停（不出图、不扣费），等用户 POST /chat/confirm。
         */
        post: operations["chat_messages_chat_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Confirm
         * @description 费用确认的显式用户动作。confirm→启 job 流式回传 job_event；cancel→作废 token。
         */
        post: operations["chat_confirm_chat_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Image
         * @description 上传产品图（Bearer）：校验大小/格式 → 落本人命名空间 → 返回 {id, url}。
         */
        post: operations["upload_image_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_uploads__upload_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/showcase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Showcase
         * @description 公开成果展示：精选出图现签 url，按清单序返回；清单空 → []。
         */
        get: operations["showcase_showcase_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_admin_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/models/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Model */
        put: operations["update_model_admin_models__name__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set User Role */
        put: operations["set_user_role_admin_users__user_id__role_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_image_uploads_post */
        Body_upload_image_uploads_post: {
            /** File */
            file: string;
        };
        /**
         * ChatConfirmRequest
         * @description POST /chat/confirm 入参（费用闸的显式用户动作）。
         */
        ChatConfirmRequest: {
            /** Session Id */
            session_id: string;
            /** Confirm Token */
            confirm_token: string;
            /**
             * Action
             * @default confirm
             */
            action: string;
        };
        /**
         * ChatMessageRequest
         * @description POST /chat/messages 入参。session_id 首轮传 null，服务端建会话经 session 事件回传。
         */
        ChatMessageRequest: {
            /** Session Id */
            session_id?: string | null;
            /** Message */
            message: string;
            /** Upload Ids */
            upload_ids?: string[];
        };
        /**
         * CloneRequest
         * @description 爆款图复刻入参（PRD §3.13，POST /listing/clone）。
         *
         *     双角色显式双字段（产品图==1 + 爆款参考图 1..2、合计 ≤3 自动满足）；喂图保序
         *     「产品前·参考后」=角色指认契约。统一要求 prompt **选填**（与单图/套图必填不同）。
         *     边界仍走 launcher fail-fast 统一 400（ISSUE-0024 口径）。
         */
        CloneRequest: {
            /** Product Upload Ids */
            product_upload_ids: string[];
            /** Reference Upload Ids */
            reference_upload_ids: string[];
            /** Clone Mode */
            clone_mode: string;
            /** Ratio */
            ratio: string;
            /**
             * Prompt
             * @default
             */
            prompt: string;
            /** Modifiers */
            modifiers?: {
                [key: string]: string;
            };
            /**
             * Category
             * @default FOOD
             */
            category: string;
        };
        /**
         * EditRequest
         * @description 二次编辑入参（PRD §3.12.13/ISSUE-0040，POST /listing/edit）。
         *
         *     生而 extra=forbid（E-⑥）：未知字段（含 overlay_texts/n/plan/category）→ 422。
         *     不收 category（R2：编辑组装无品类块、库无列，死参数不收）。
         *     prompt 必填走 schema 严校 422（E-⑤，#652/#654 拍定与 forbid 同层同码）；
         *     edit_mode/ratio 仍走 launcher fail-fast 400（域值校验，单一事实源在卡/映射表）。
         */
        EditRequest: {
            /** Source Image Key */
            source_image_key: string;
            /** Prompt */
            prompt: string;
            /**
             * Edit Mode
             * @default delta
             */
            edit_mode: string;
            /** Modifiers */
            modifiers?: {
                [key: string]: string;
            };
            /** Ratio */
            ratio?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ListingGenerateRequest
         * @description listing 出图入参（两步流：图先经 POST /uploads，这里只带 upload_ids）。
         *
         *     数量/范围/比例/下拉的具体边界在 launcher 同步 fail-fast 校验（统一 400），不靠 Pydantic 约束
         *     （避免 422 与 spec 的 400 口径不一致，ISSUE-0024）。
         */
        ListingGenerateRequest: {
            /** Upload Ids */
            upload_ids: string[];
            /** Prompt */
            prompt: string;
            /** Ratio */
            ratio: string;
            /** N */
            n?: number | null;
            /** Plan */
            plan?: {
                [key: string]: number;
            } | null;
            /** Overlay Texts */
            overlay_texts?: string[] | null;
            /** Modifiers */
            modifiers?: {
                [key: string]: string;
            };
            /**
             * Category
             * @default FOOD
             */
            category: string;
        };
        /** ListingImageOut */
        ListingImageOut: {
            /** Url */
            url: string;
            /** Image Key */
            image_key: string;
            /** Seed */
            seed: number;
            /** Cost */
            cost: string;
            /** Status */
            status: string;
            /** Image Type */
            image_type?: string | null;
        };
        /** ListingJobDetailOut */
        ListingJobDetailOut: {
            /** Job Id */
            job_id: string;
            /** Prompt */
            prompt: string;
            /** Modifiers */
            modifiers: {
                [key: string]: string;
            };
            /** Platform */
            platform: string | null;
            /** Ratio */
            ratio: string;
            /** Size */
            size: string;
            /** N */
            n: number;
            /** Status */
            status: string;
            /** Total Cost */
            total_cost: string;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Images */
            images: components["schemas"]["ListingImageOut"][];
            /** Input Urls */
            input_urls: string[];
            /** Clone Mode */
            clone_mode?: string | null;
            /**
             * Input Roles
             * @default []
             */
            input_roles: (string | null)[];
            /** Parent Job Id */
            parent_job_id?: string | null;
            /** Edit Mode */
            edit_mode?: string | null;
            /** Source Image Url */
            source_image_url?: string | null;
            /** Source Image Type */
            source_image_type?: string | null;
            /** Chain Cost */
            chain_cost?: string | null;
        };
        /** ListingJobSummaryOut */
        ListingJobSummaryOut: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Platform */
            platform: string | null;
            /** Ratio */
            ratio: string;
            /** N */
            n: number;
            /** Total Cost */
            total_cost: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** First Image Url */
            first_image_url: string | null;
            /** Image Count */
            image_count: number;
            /** Edit Mode */
            edit_mode?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Jwt */
            jwt: string;
            role: components["schemas"]["Role"];
            /** Name */
            name: string;
        };
        /** MeResponse */
        MeResponse: {
            /** User Id */
            user_id: string;
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /** Dept */
            dept: string | null;
        };
        /** ModelConfigOut */
        ModelConfigOut: {
            /** Name */
            name: string;
            /** Unit Cost */
            unit_cost: string;
            /** Enabled */
            enabled: boolean;
            /** Extra */
            extra: {
                [key: string]: unknown;
            };
        };
        /**
         * ModelConfigUpdate
         * @description 部分更新：仅传入的字段生效（None = 不改）。
         */
        ModelConfigUpdate: {
            /** Unit Cost */
            unit_cost?: number | string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            } | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /**
         * Role
         * @description 系统角色：值=app_user.role 的 DB 字符串契约（改值=数据迁移，须用户签字）。
         * @enum {string}
         */
        Role: "设计师" | "管理者";
        /** RoleUpdate */
        RoleUpdate: {
            role: components["schemas"]["Role"];
        };
        /**
         * ShowcaseItemOut
         * @description GET /showcase 列表项：现签 url + 图型 + 首页说明（公开，无用户数据）。
         */
        ShowcaseItemOut: {
            /** Url */
            url: string;
            /** Image Type */
            image_type: string;
            /** Caption */
            caption: string;
        };
        /**
         * UploadResponse
         * @description POST /uploads 响应：上传图 id + 预览代理 url（GET /uploads/{id}）。
         */
        UploadResponse: {
            /** Id */
            id: string;
            /** Url */
            url: string;
        };
        /**
         * UserOut
         * @description 用户管理列表项。**不含 password_hash**。
         */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_listing_listing_generate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_listing_listing_clone_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloneRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_listing_listing_edit_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_listing_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                q?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingJobSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_listing_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingJobDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listing_events_listing__job_id__events_get: {
        parameters: {
            query?: {
                access_token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_messages_chat_messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_confirm_chat_confirm_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_uploads_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_uploads__upload_id__get: {
        parameters: {
            query?: {
                access_token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    showcase_showcase_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShowcaseItemOut"][];
                };
            };
        };
    };
    list_models_admin_models_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_admin_models__name__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_admin_users_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_role_admin_users__user_id__role_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
