Syslog                  no
LogWhy                  yes
Mode                    s
Canonicalization        relaxed/simple
Socket                  inet:8891@0.0.0.0
PidFile                 /run/opendkim/opendkim.pid
UserID                  opendkim
UMask                   007
KeyTable                file:/etc/opendkim/KeyTable
SigningTable            refile:/etc/opendkim/SigningTable
InternalHosts           file:/etc/opendkim/TrustedHosts
ExternalIgnoreList      file:/etc/opendkim/TrustedHosts
OversignHeaders         From
RequireSafeKeys         true
